# FROM python:3.11-slim

# WORKDIR /app
# COPY ../requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt

# COPY ../ui /app/ui
# EXPOSE 8501
# CMD ["streamlit", "run", "ui/App.py", "--server.port=8501", "--server.address=0.0.0.0"]

# infra/Dockerfile.ui
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ui/ /app/ui/

EXPOSE 8501
CMD ["streamlit", "run", "ui/App.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
