FROM python:3.11-slim

WORKDIR /app
COPY ../requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ../ui /app/ui
EXPOSE 8501
CMD ["streamlit", "run", "ui/App.py", "--server.port=8501", "--server.address=0.0.0.0"]
