version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ai_cost_db
    restart: always
    environment:
      POSTGRES_DB: ai_cost
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_cost_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: ai_cost_api
    ports:
      - "8000:8000"
    volumes:
      - ../api:/app/api
      - ../requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ai_cost
      - DB_USER=ai_user
      - DB_PASSWORD=ai_password
    depends_on:
      - db

  ui:
    build:
      context: ..
      dockerfile: infra/Dockerfile.ui
    container_name: ai_cost_ui
    ports:
      - "8501:8501"
    volumes:
      - ../ui:/app/ui
      - ../requirements.txt:/app/requirements.txt
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

volumes:
  dbdata:
